baseURL = 'https://pedrocoelhopais.github.io/website/'
languageCode = 'en-us'
title = "Rabbit's Den"
theme = "smol"

# Parameters
[params]
    subtitle = "A website from Pedro Coelho Pais"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
    [[menu.footer]]
        name = "Github"
        url = "https://github.com/pedrocoelhopais"
        weight = 1 

    [[menu.footer]]
        name = "Linked In"
        url = "https://www.linkedin.com/in/its-pedro-baybeh/"
        weight = 2 

    [[menu.footer]]
        name = "Chess"
        url = "https://www.chess.com/member/ph_nes"
        weight = 3
